### PR TITLE
Update vscode-jsonrpc dependency

### PR DESCRIPTION
**Pull request by CGNonofr**
This update is needed to be able to update monaco-languageclient to the last verstion of monaco-editor/vscode-jsonrpc/vscode-languageclient/vscode-languageserver

The code of the future MR on monaco-languageclient is already ready and working, waiting for this one

### CODE REVIEW

**Comment by CGNonofr** [comment]
Is this an issue that it doesn't compile anymore with node6?

Node6 seems to not be supported anymore, and Typescript 4 crashes with it

Typescript 4 is required because vscode-jsonrpc uses the new `import type` syntax

**Comment by CGNonofr** [comment]
Is there anything I can to in order to get it merged/release so I can create the MR on `monaco-languageclient`?

**Comment by Oliver-Weng-Sorcerer** [comment]
when will this be merged ?
we need this for upgrading monaco to latest.

**Comment by CGNonofr** [comment]
The update was merged and published from https://github.com/CodinGame/monaco-jsonrpc to `@codingame/monaco-jsonrpc`

**Pull request closed without merging**
