### PR TITLE
Switch target to es6

### LINKED ISSUE #8: TypeError: Class constructor AbstractMessageReader cannot be invoked without 'new'
`vscode-ws-jsonrpc` uses `target: es5`, which transpiles classes to functions. But `vscode-jsonrpc` uses `target: es6`, which does not transpile classes. Therefor classes that inherit from classes in `vscode-jsonrpc` error when trying to instantiate them.

### PR DESCRIPTION
**Pull request by felixfbecker**
Fixes #8

### CODE REVIEW

**Comment by felixfbecker** [comment]
@akosyakov @svenefftinge could one of you take a look? I published this as https://www.npmjs.com/package/@sourcegraph/vscode-ws-jsonrpc but would prefer to depend on upstream

**Comment by netweng** [comment]
i do this locally and compile the vscode-jsonrpc to es6, it did solved my problem. and i just wander when this pr can be merged into master, and vscod-jsonrpc can update its version? otherwise i need to compile it by myself and use unofficial package

**Comment by akosyakov** [comment]
We don't have plans to switch to es6, since it causes integration issues between es5 and es6 code between different dependencies. As soon as we resolve them, we will consider you PR, thank you. For now, you can fork and transpile it. Maybe there is a way to distribute both es5 and es6 from the same repo. We could consider it.

**Comment by felixfbecker** [comment]
Hey @akosyakov thanks for your response. Which integration issues between dependencies do you mean specifically? As explained in the linked issue, `vscode-jsonrpc` (which is a dependency of this package) uses target ES6, so _not_ using ES6 actually creates an integration issue between dependencies here and makes it impossible to use this package without a bundler that transpiles _everything_ to ES5 (an error is always thrown).

**Comment by akosyakov** [comment]
In Theia we extend classes from this package in es5 code. We cannot move Theia completely to es6 because we have other dependencies which are using es5 still and extending es5 from es6 does not work as well. I'm looking for a cut right now to have mix of es5 and es6 code without inheritance between classes. Anyway I will publish a version compiled to `es6` under `es6` npm tag. You can use it instead.

**Comment by felixfbecker** [comment]
I'm assuming Theia is using a transpiler like webpack + Babel. Can't it transpile the ES6 of this package to ES5 during bundle time? You'd just need to make sure you're not ignoring all of `node_modules` in your webpack config (I think that's a bad practice anyway because it means there is no guarantee the bundle works in the browsers you expect it to work in, but you could also only whitelist this package).

**Comment by akosyakov** [comment]
> I'm assuming Theia is using a transpiler like webpack + Babel.

Not yet, but maybe we have to end up there, would like to avoid to add another tool for now.

**Comment by akosyakov** [comment]
You can use 0.1.1, it is compiled to es6. `latest` points to 0.1.0 for now, which is `es5`. If everything is good in downstream i will update `latest` to 0.1.1 this or next week.

**Pull request closed without merging**
